apiVersion: v1
kind: Service
metadata:
  name: autosource-api-service
spec:
  type: ClusterIP
  # type: NodePort
  selector:
    app: autosource-api
  ports:
  - name: autosource-api-port
    port: 8087
    targetPort: 8087
