apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: autosource
resources:
  - ../ConfigMap/global-config.yaml
  - ../Volume/mariadb-pv.yaml
  - ../Volume/mariadb-pvc.yaml
  - ../MariaDB/mariadb-deployment.yaml
  - ../MariaDB/mariadb-service.yaml
  - ../Backend/backend-deployment.yaml
  - ../Backend/backend-service.yaml
  - ../Frontend/frontend-deployment.yaml
  - ../Frontend/frontend-service.yaml
  - ../ingress.yaml
