apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: autosource
resources:
  - global-config.yaml
  - mariadb-pv.yaml
  - mariadb-pvc.yaml
  - mariadb-deployment.yaml
  - mariadb-service.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - ingress.yaml
